repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - pep8-naming
          - flake8-use-fstring
          - flake8-isort
          - flake8-docstrings
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: test/run-in-env.sh pylint
        language: system
        types: [python]
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]
      - id: mypy
        name: mypy
        entry: test/run-in-env.sh mypy
        language: script
        types: [python]
        require_serial: true
        files: ^src/python/.+\.py$
