[tool.isort]
profile = 'black'

[tool.pylint."MASTER"]
init-hook='import sys; sys.path.append("src/python/sensu_plugin/lib")'

[tool.pylint."LOGGING"]
disable=[
  "logging-fstring-interpolation"
]

[tool.pylint."BASE"]
disable=[
  "line-too-long" # black takes care of this
]
good-names=[
  "rc"
]